variable "org_id" {}
variable "prj_id" {}
variable "env" {}
variable "zone" {}
variable "sharedvpc_project" {}
variable "sharedvpc_name" {}
variable "sharedvpc_region" {}
variable "sharedvpc_front" {}
variable "sharedvpc_backend" {}
